Repository VovaKyrylenko/ice-cream, pull requests merged in 2022-10, with the labels that each got.

#18 add franchise-modal html
  src/partials/franches-modal.html
Labels: wontfix

#29 G-1 html and scss
  src/partials/gallery.html
  src/sass/layouts/_gallery.scss
Labels: invalid, wontfix

#31 ad-1 убрала span и p из svg
  src/partials/advantages.html
  src/sass/layouts/_advantages.scss
Labels: invalid, question, wontfix
